export const GET_RESOURCES = "GET_RESOURCES";
export const GET_RESOURCES_SUCC = "GET_RESOURCES_SUCC";
export const GET_RESOURCES_ERR = "GET_RESOURCES_ERR";


export const GET_THREE_RESOURCE = "GET_THREE_RESOURCE";
export const GET_THREE_SUCC = "GET_THREE_SUCC";
export const GET_THREE_ERR = "GET_THREE_ERR";


export const GET_TOPOTHERS_RESOURCE = "GET_TOPOTHERS_RESOURCE";
export const GET_TOPOHTERS_SUCC = "GET_TOPOHTERS_SUCC";
export const GET_TOPOTHERS_ERR = "GET_TOPOHTERS_ERR";